### ISSUE TITLE
Failed to load local LLM file

### ISSUE THREAD

**Issue by Datou** [get-salt-AI/SaltAI_Language_Toolkit#6]
![image](https://github.com/user-attachments/assets/a7643a2a-dc2b-4e42-8961-f05aa4ee6d14)

**Comment by WAS-PlaiLabs** [comment]
I am not able to reproduce this myself. Did you restart ComfyUI? When I moved my model to the llm directory, the `Refresh` button didn't work. Never showed. So I had to restart ComfyUI.

![image](https://github.com/user-attachments/assets/005b2009-0069-494c-9a7f-ba190689bf22)

**Comment by Datou** [comment]
restart works!
![image](https://github.com/user-attachments/assets/898aca69-4437-4c32-978a-5aa9e0dfd79a)
